<?php

namespace App\Modules\Narrative\Dto;

/**
 * NarrativeSignal: The deterministic deltas to be applied to the simulation.
 * Generated by the SignalBuilder based on NarrativeMeaning.
 */
class NarrativeSignal
{
    public function __construct(
        public readonly float $entropyDelta = 0.0,
        public readonly float $stabilityDelta = 0.0,
        public readonly array $metadata = []
    ) {}
}
