version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000"
  relay: pipes

http:
  address: "0.0.0.0:8000"
  middleware: ["static"]
  static:
    dir: "public"
    forbid: ["*.php"]
  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: production
  level: debug
  encoding: json
