<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.ActorSoaOutput</code>
 */
class ActorSoaOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 action_id = 1;</code>
     */
    protected $action_id = 0;
    /**
     * Generated from protobuf field <code>float new_hunger = 2;</code>
     */
    protected $new_hunger = 0.0;
    /**
     * Generated from protobuf field <code>float new_energy = 3;</code>
     */
    protected $new_energy = 0.0;
    /**
     * Generated from protobuf field <code>float new_trauma = 4;</code>
     */
    protected $new_trauma = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action_id
     *     @type float $new_hunger
     *     @type float $new_energy
     *     @type float $new_trauma
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 action_id = 1;</code>
     * @return int
     */
    public function getActionId()
    {
        return $this->action_id;
    }

    /**
     * Generated from protobuf field <code>uint32 action_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setActionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->action_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float new_hunger = 2;</code>
     * @return float
     */
    public function getNewHunger()
    {
        return $this->new_hunger;
    }

    /**
     * Generated from protobuf field <code>float new_hunger = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setNewHunger($var)
    {
        GPBUtil::checkFloat($var);
        $this->new_hunger = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float new_energy = 3;</code>
     * @return float
     */
    public function getNewEnergy()
    {
        return $this->new_energy;
    }

    /**
     * Generated from protobuf field <code>float new_energy = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setNewEnergy($var)
    {
        GPBUtil::checkFloat($var);
        $this->new_energy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float new_trauma = 4;</code>
     * @return float
     */
    public function getNewTrauma()
    {
        return $this->new_trauma;
    }

    /**
     * Generated from protobuf field <code>float new_trauma = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setNewTrauma($var)
    {
        GPBUtil::checkFloat($var);
        $this->new_trauma = $var;

        return $this;
    }

}

