<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.AdvanceResponse</code>
 */
class AdvanceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     */
    protected $ok = false;
    /**
     * Generated from protobuf field <code>string error_message = 2;</code>
     */
    protected $error_message = '';
    /**
     * Generated from protobuf field <code>.worldos.simulation.UniverseSnapshot snapshot = 3;</code>
     */
    protected $snapshot = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $ok
     *     @type string $error_message
     *     @type \Worldos\Simulation\UniverseSnapshot $snapshot
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     * @return bool
     */
    public function getOk()
    {
        return $this->ok;
    }

    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOk($var)
    {
        GPBUtil::checkBool($var);
        $this->ok = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 2;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.worldos.simulation.UniverseSnapshot snapshot = 3;</code>
     * @return \Worldos\Simulation\UniverseSnapshot|null
     */
    public function getSnapshot()
    {
        return $this->snapshot;
    }

    public function hasSnapshot()
    {
        return isset($this->snapshot);
    }

    public function clearSnapshot()
    {
        unset($this->snapshot);
    }

    /**
     * Generated from protobuf field <code>.worldos.simulation.UniverseSnapshot snapshot = 3;</code>
     * @param \Worldos\Simulation\UniverseSnapshot $var
     * @return $this
     */
    public function setSnapshot($var)
    {
        GPBUtil::checkMessage($var, \Worldos\Simulation\UniverseSnapshot::class);
        $this->snapshot = $var;

        return $this;
    }

}

