<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.AdvanceRequest</code>
 */
class AdvanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     */
    protected $universe_id = 0;
    /**
     * Generated from protobuf field <code>uint64 ticks = 2;</code>
     */
    protected $ticks = 0;
    /**
     * Optional: serialized state to load (e.g. from Laravel). Empty = load from store.
     *
     * Generated from protobuf field <code>bytes state_input = 3;</code>
     */
    protected $state_input = '';
    /**
     * Metadata about the World (Axioms, Origin, etc.)
     *
     * Generated from protobuf field <code>.worldos.simulation.WorldConfig world_config = 4;</code>
     */
    protected $world_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $universe_id
     *     @type int|string $ticks
     *     @type string $state_input
     *           Optional: serialized state to load (e.g. from Laravel). Empty = load from store.
     *     @type \Worldos\Simulation\WorldConfig $world_config
     *           Metadata about the World (Axioms, Origin, etc.)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     * @return int|string
     */
    public function getUniverseId()
    {
        return $this->universe_id;
    }

    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUniverseId($var)
    {
        GPBUtil::checkUint64($var);
        $this->universe_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ticks = 2;</code>
     * @return int|string
     */
    public function getTicks()
    {
        return $this->ticks;
    }

    /**
     * Generated from protobuf field <code>uint64 ticks = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTicks($var)
    {
        GPBUtil::checkUint64($var);
        $this->ticks = $var;

        return $this;
    }

    /**
     * Optional: serialized state to load (e.g. from Laravel). Empty = load from store.
     *
     * Generated from protobuf field <code>bytes state_input = 3;</code>
     * @return string
     */
    public function getStateInput()
    {
        return $this->state_input;
    }

    /**
     * Optional: serialized state to load (e.g. from Laravel). Empty = load from store.
     *
     * Generated from protobuf field <code>bytes state_input = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStateInput($var)
    {
        GPBUtil::checkString($var, False);
        $this->state_input = $var;

        return $this;
    }

    /**
     * Metadata about the World (Axioms, Origin, etc.)
     *
     * Generated from protobuf field <code>.worldos.simulation.WorldConfig world_config = 4;</code>
     * @return \Worldos\Simulation\WorldConfig|null
     */
    public function getWorldConfig()
    {
        return $this->world_config;
    }

    public function hasWorldConfig()
    {
        return isset($this->world_config);
    }

    public function clearWorldConfig()
    {
        unset($this->world_config);
    }

    /**
     * Metadata about the World (Axioms, Origin, etc.)
     *
     * Generated from protobuf field <code>.worldos.simulation.WorldConfig world_config = 4;</code>
     * @param \Worldos\Simulation\WorldConfig $var
     * @return $this
     */
    public function setWorldConfig($var)
    {
        GPBUtil::checkMessage($var, \Worldos\Simulation\WorldConfig::class);
        $this->world_config = $var;

        return $this;
    }

}

