<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.BatchAdvanceResponse</code>
 */
class BatchAdvanceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .worldos.simulation.AdvanceResponse responses = 1;</code>
     */
    private $responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Worldos\Simulation\AdvanceResponse>|\Google\Protobuf\Internal\RepeatedField $responses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .worldos.simulation.AdvanceResponse responses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * Generated from protobuf field <code>repeated .worldos.simulation.AdvanceResponse responses = 1;</code>
     * @param array<\Worldos\Simulation\AdvanceResponse>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Worldos\Simulation\AdvanceResponse::class);
        $this->responses = $arr;

        return $this;
    }

}

