<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.CalculateVocationAlignmentRequest</code>
 */
class CalculateVocationAlignmentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string actor_motivation_json = 1;</code>
     */
    protected $actor_motivation_json = '';
    /**
     * Generated from protobuf field <code>string target_profile_json = 2;</code>
     */
    protected $target_profile_json = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $actor_motivation_json
     *     @type string $target_profile_json
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string actor_motivation_json = 1;</code>
     * @return string
     */
    public function getActorMotivationJson()
    {
        return $this->actor_motivation_json;
    }

    /**
     * Generated from protobuf field <code>string actor_motivation_json = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setActorMotivationJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->actor_motivation_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_profile_json = 2;</code>
     * @return string
     */
    public function getTargetProfileJson()
    {
        return $this->target_profile_json;
    }

    /**
     * Generated from protobuf field <code>string target_profile_json = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetProfileJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_profile_json = $var;

        return $this;
    }

}

