<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.CalculateVocationAlignmentResponse</code>
 */
class CalculateVocationAlignmentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float alignment = 1;</code>
     */
    protected $alignment = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $alignment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float alignment = 1;</code>
     * @return float
     */
    public function getAlignment()
    {
        return $this->alignment;
    }

    /**
     * Generated from protobuf field <code>float alignment = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setAlignment($var)
    {
        GPBUtil::checkFloat($var);
        $this->alignment = $var;

        return $this;
    }

}

