<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.ComputeMetabolismGridResponse</code>
 */
class ComputeMetabolismGridResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double total_waste = 1;</code>
     */
    protected $total_waste = 0.0;
    /**
     * Generated from protobuf field <code>repeated double populations = 2;</code>
     */
    private $populations;
    /**
     * Generated from protobuf field <code>repeated double biomasses = 3;</code>
     */
    private $biomasses;
    /**
     * Generated from protobuf field <code>repeated double net_energies = 4;</code>
     */
    private $net_energies;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $total_waste
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $populations
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $biomasses
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $net_energies
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double total_waste = 1;</code>
     * @return float
     */
    public function getTotalWaste()
    {
        return $this->total_waste;
    }

    /**
     * Generated from protobuf field <code>double total_waste = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalWaste($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_waste = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double populations = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPopulations()
    {
        return $this->populations;
    }

    /**
     * Generated from protobuf field <code>repeated double populations = 2;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPopulations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->populations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double biomasses = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBiomasses()
    {
        return $this->biomasses;
    }

    /**
     * Generated from protobuf field <code>repeated double biomasses = 3;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBiomasses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->biomasses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double net_energies = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetEnergies()
    {
        return $this->net_energies;
    }

    /**
     * Generated from protobuf field <code>repeated double net_energies = 4;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetEnergies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->net_energies = $arr;

        return $this;
    }

}

