<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.ComputeMetabolismGridRequest</code>
 */
class ComputeMetabolismGridRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated double populations = 1;</code>
     */
    private $populations;
    /**
     * Generated from protobuf field <code>repeated double biomasses = 2;</code>
     */
    private $biomasses;
    /**
     * Generated from protobuf field <code>repeated double industries = 3;</code>
     */
    private $industries;
    /**
     * Generated from protobuf field <code>double efficiency = 4;</code>
     */
    protected $efficiency = 0.0;
    /**
     * Generated from protobuf field <code>double base_energy = 5;</code>
     */
    protected $base_energy = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $populations
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $biomasses
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $industries
     *     @type float $efficiency
     *     @type float $base_energy
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated double populations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPopulations()
    {
        return $this->populations;
    }

    /**
     * Generated from protobuf field <code>repeated double populations = 1;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPopulations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->populations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double biomasses = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBiomasses()
    {
        return $this->biomasses;
    }

    /**
     * Generated from protobuf field <code>repeated double biomasses = 2;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBiomasses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->biomasses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double industries = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndustries()
    {
        return $this->industries;
    }

    /**
     * Generated from protobuf field <code>repeated double industries = 3;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndustries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->industries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double efficiency = 4;</code>
     * @return float
     */
    public function getEfficiency()
    {
        return $this->efficiency;
    }

    /**
     * Generated from protobuf field <code>double efficiency = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setEfficiency($var)
    {
        GPBUtil::checkDouble($var);
        $this->efficiency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double base_energy = 5;</code>
     * @return float
     */
    public function getBaseEnergy()
    {
        return $this->base_energy;
    }

    /**
     * Generated from protobuf field <code>double base_energy = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseEnergy($var)
    {
        GPBUtil::checkDouble($var);
        $this->base_energy = $var;

        return $this;
    }

}

