<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.EvaluateRulesRequest</code>
 */
class EvaluateRulesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string state_json = 1;</code>
     */
    protected $state_json = '';
    /**
     * Generated from protobuf field <code>string rules_dsl = 2;</code>
     */
    protected $rules_dsl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $state_json
     *     @type string $rules_dsl
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string state_json = 1;</code>
     * @return string
     */
    public function getStateJson()
    {
        return $this->state_json;
    }

    /**
     * Generated from protobuf field <code>string state_json = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStateJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->state_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rules_dsl = 2;</code>
     * @return string
     */
    public function getRulesDsl()
    {
        return $this->rules_dsl;
    }

    /**
     * Generated from protobuf field <code>string rules_dsl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRulesDsl($var)
    {
        GPBUtil::checkString($var, True);
        $this->rules_dsl = $var;

        return $this;
    }

}

