<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.GetCombinedGravityResponse</code>
 */
class GetCombinedGravityResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float gravity = 1;</code>
     */
    protected $gravity = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $gravity
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float gravity = 1;</code>
     * @return float
     */
    public function getGravity()
    {
        return $this->gravity;
    }

    /**
     * Generated from protobuf field <code>float gravity = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setGravity($var)
    {
        GPBUtil::checkFloat($var);
        $this->gravity = $var;

        return $this;
    }

}

