<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.GetCombinedGravityRequest</code>
 */
class GetCombinedGravityRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string rulesets_json = 1;</code>
     */
    protected $rulesets_json = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $rulesets_json
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string rulesets_json = 1;</code>
     * @return string
     */
    public function getRulesetsJson()
    {
        return $this->rulesets_json;
    }

    /**
     * Generated from protobuf field <code>string rulesets_json = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRulesetsJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->rulesets_json = $var;

        return $this;
    }

}

