<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.KernelGenome</code>
 */
class KernelGenome extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double diffusion_rate = 1;</code>
     */
    protected $diffusion_rate = 0.0;
    /**
     * Generated from protobuf field <code>double entropy_coefficient = 2;</code>
     */
    protected $entropy_coefficient = 0.0;
    /**
     * Generated from protobuf field <code>double mutation_rate = 3;</code>
     */
    protected $mutation_rate = 0.0;
    /**
     * Generated from protobuf field <code>double attractor_gravity = 4;</code>
     */
    protected $attractor_gravity = 0.0;
    /**
     * Generated from protobuf field <code>double complexity_bonus = 5;</code>
     */
    protected $complexity_bonus = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $diffusion_rate
     *     @type float $entropy_coefficient
     *     @type float $mutation_rate
     *     @type float $attractor_gravity
     *     @type float $complexity_bonus
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double diffusion_rate = 1;</code>
     * @return float
     */
    public function getDiffusionRate()
    {
        return $this->diffusion_rate;
    }

    /**
     * Generated from protobuf field <code>double diffusion_rate = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setDiffusionRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->diffusion_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double entropy_coefficient = 2;</code>
     * @return float
     */
    public function getEntropyCoefficient()
    {
        return $this->entropy_coefficient;
    }

    /**
     * Generated from protobuf field <code>double entropy_coefficient = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setEntropyCoefficient($var)
    {
        GPBUtil::checkDouble($var);
        $this->entropy_coefficient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double mutation_rate = 3;</code>
     * @return float
     */
    public function getMutationRate()
    {
        return $this->mutation_rate;
    }

    /**
     * Generated from protobuf field <code>double mutation_rate = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMutationRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->mutation_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double attractor_gravity = 4;</code>
     * @return float
     */
    public function getAttractorGravity()
    {
        return $this->attractor_gravity;
    }

    /**
     * Generated from protobuf field <code>double attractor_gravity = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAttractorGravity($var)
    {
        GPBUtil::checkDouble($var);
        $this->attractor_gravity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double complexity_bonus = 5;</code>
     * @return float
     */
    public function getComplexityBonus()
    {
        return $this->complexity_bonus;
    }

    /**
     * Generated from protobuf field <code>double complexity_bonus = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setComplexityBonus($var)
    {
        GPBUtil::checkDouble($var);
        $this->complexity_bonus = $var;

        return $this;
    }

}

