<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.MergeRequest</code>
 */
class MergeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes state_a = 1;</code>
     */
    protected $state_a = '';
    /**
     * Generated from protobuf field <code>bytes state_b = 2;</code>
     */
    protected $state_b = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $state_a
     *     @type string $state_b
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes state_a = 1;</code>
     * @return string
     */
    public function getStateA()
    {
        return $this->state_a;
    }

    /**
     * Generated from protobuf field <code>bytes state_a = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStateA($var)
    {
        GPBUtil::checkString($var, False);
        $this->state_a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes state_b = 2;</code>
     * @return string
     */
    public function getStateB()
    {
        return $this->state_b;
    }

    /**
     * Generated from protobuf field <code>bytes state_b = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStateB($var)
    {
        GPBUtil::checkString($var, False);
        $this->state_b = $var;

        return $this;
    }

}

