<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.ObserveRequest</code>
 */
class ObserveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     */
    protected $universe_id = 0;
    /**
     * Generated from protobuf field <code>uint32 zone_index = 2;</code>
     */
    protected $zone_index = 0;
    /**
     * 1.0 = Full observation (Force collapse)
     *
     * Generated from protobuf field <code>double intensity = 3;</code>
     */
    protected $intensity = 0.0;
    /**
     * Generated from protobuf field <code>bytes state_input = 4;</code>
     */
    protected $state_input = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $universe_id
     *     @type int $zone_index
     *     @type float $intensity
     *           1.0 = Full observation (Force collapse)
     *     @type string $state_input
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     * @return int|string
     */
    public function getUniverseId()
    {
        return $this->universe_id;
    }

    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUniverseId($var)
    {
        GPBUtil::checkUint64($var);
        $this->universe_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 zone_index = 2;</code>
     * @return int
     */
    public function getZoneIndex()
    {
        return $this->zone_index;
    }

    /**
     * Generated from protobuf field <code>uint32 zone_index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setZoneIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->zone_index = $var;

        return $this;
    }

    /**
     * 1.0 = Full observation (Force collapse)
     *
     * Generated from protobuf field <code>double intensity = 3;</code>
     * @return float
     */
    public function getIntensity()
    {
        return $this->intensity;
    }

    /**
     * 1.0 = Full observation (Force collapse)
     *
     * Generated from protobuf field <code>double intensity = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setIntensity($var)
    {
        GPBUtil::checkDouble($var);
        $this->intensity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes state_input = 4;</code>
     * @return string
     */
    public function getStateInput()
    {
        return $this->state_input;
    }

    /**
     * Generated from protobuf field <code>bytes state_input = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStateInput($var)
    {
        GPBUtil::checkString($var, False);
        $this->state_input = $var;

        return $this;
    }

}

