<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.ProcessFieldsV7Response</code>
 */
class ProcessFieldsV7Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated double fields = 1;</code>
     */
    private $fields;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $fields
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated double fields = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated double fields = 1;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->fields = $arr;

        return $this;
    }

}

