<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.ProcessFieldsV7Request</code>
 */
class ProcessFieldsV7Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Flattened [count * 8]
     *
     * Generated from protobuf field <code>repeated double fields = 1;</code>
     */
    private $fields;
    /**
     * Generated from protobuf field <code>repeated uint32 neighbor_counts = 2;</code>
     */
    private $neighbor_counts;
    /**
     * Generated from protobuf field <code>repeated uint32 neighbor_offsets = 3;</code>
     */
    private $neighbor_offsets;
    /**
     * Generated from protobuf field <code>repeated uint32 neighbors = 4;</code>
     */
    private $neighbors;
    /**
     * Generated from protobuf field <code>double diffusion_rate = 5;</code>
     */
    protected $diffusion_rate = 0.0;
    /**
     * Generated from protobuf field <code>double preservation_rate = 6;</code>
     */
    protected $preservation_rate = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $fields
     *           Flattened [count * 8]
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $neighbor_counts
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $neighbor_offsets
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $neighbors
     *     @type float $diffusion_rate
     *     @type float $preservation_rate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Flattened [count * 8]
     *
     * Generated from protobuf field <code>repeated double fields = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Flattened [count * 8]
     *
     * Generated from protobuf field <code>repeated double fields = 1;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->fields = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 neighbor_counts = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNeighborCounts()
    {
        return $this->neighbor_counts;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 neighbor_counts = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNeighborCounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->neighbor_counts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 neighbor_offsets = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNeighborOffsets()
    {
        return $this->neighbor_offsets;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 neighbor_offsets = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNeighborOffsets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->neighbor_offsets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 neighbors = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNeighbors()
    {
        return $this->neighbors;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 neighbors = 4;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNeighbors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->neighbors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double diffusion_rate = 5;</code>
     * @return float
     */
    public function getDiffusionRate()
    {
        return $this->diffusion_rate;
    }

    /**
     * Generated from protobuf field <code>double diffusion_rate = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDiffusionRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->diffusion_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double preservation_rate = 6;</code>
     * @return float
     */
    public function getPreservationRate()
    {
        return $this->preservation_rate;
    }

    /**
     * Generated from protobuf field <code>double preservation_rate = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setPreservationRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->preservation_rate = $var;

        return $this;
    }

}

