<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.ProcessActorsSoaRequest</code>
 */
class ProcessActorsSoaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 tick = 1;</code>
     */
    protected $tick = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 ids = 2;</code>
     */
    private $ids;
    /**
     * Generated from protobuf field <code>repeated uint32 zone_ids = 3;</code>
     */
    private $zone_ids;
    /**
     * Generated from protobuf field <code>repeated float hunger = 4;</code>
     */
    private $hunger;
    /**
     * Generated from protobuf field <code>repeated float energy = 5;</code>
     */
    private $energy;
    /**
     * Generated from protobuf field <code>repeated float fear = 6;</code>
     */
    private $fear;
    /**
     * Generated from protobuf field <code>repeated float trauma = 7;</code>
     */
    private $trauma;
    /**
     * Generated from protobuf field <code>repeated uint32 heroic_types = 8;</code>
     */
    private $heroic_types;
    /**
     * Generated from protobuf field <code>repeated uint64 lineage_ids = 9;</code>
     */
    private $lineage_ids;
    /**
     * Generated from protobuf field <code>repeated uint64 memes = 10;</code>
     */
    private $memes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $tick
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $ids
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $zone_ids
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $hunger
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $energy
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $fear
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $trauma
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $heroic_types
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $lineage_ids
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $memes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 tick = 1;</code>
     * @return int|string
     */
    public function getTick()
    {
        return $this->tick;
    }

    /**
     * Generated from protobuf field <code>uint64 tick = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTick($var)
    {
        GPBUtil::checkUint64($var);
        $this->tick = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 ids = 2;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 zone_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getZoneIds()
    {
        return $this->zone_ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 zone_ids = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setZoneIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->zone_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float hunger = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHunger()
    {
        return $this->hunger;
    }

    /**
     * Generated from protobuf field <code>repeated float hunger = 4;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHunger($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->hunger = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float energy = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEnergy()
    {
        return $this->energy;
    }

    /**
     * Generated from protobuf field <code>repeated float energy = 5;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEnergy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->energy = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float fear = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFear()
    {
        return $this->fear;
    }

    /**
     * Generated from protobuf field <code>repeated float fear = 6;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFear($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->fear = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float trauma = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrauma()
    {
        return $this->trauma;
    }

    /**
     * Generated from protobuf field <code>repeated float trauma = 7;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrauma($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->trauma = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 heroic_types = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeroicTypes()
    {
        return $this->heroic_types;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 heroic_types = 8;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeroicTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->heroic_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 lineage_ids = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLineageIds()
    {
        return $this->lineage_ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 lineage_ids = 9;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLineageIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->lineage_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 memes = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemes()
    {
        return $this->memes;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 memes = 10;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->memes = $arr;

        return $this;
    }

}

