<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.RegimeTransition</code>
 */
class RegimeTransition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 from_tick = 1;</code>
     */
    protected $from_tick = 0;
    /**
     * Generated from protobuf field <code>uint64 to_tick = 2;</code>
     */
    protected $to_tick = 0;
    /**
     * how far the jump was
     *
     * Generated from protobuf field <code>double distance = 3;</code>
     */
    protected $distance = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $from_tick
     *     @type int|string $to_tick
     *     @type float $distance
     *           how far the jump was
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 from_tick = 1;</code>
     * @return int|string
     */
    public function getFromTick()
    {
        return $this->from_tick;
    }

    /**
     * Generated from protobuf field <code>uint64 from_tick = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFromTick($var)
    {
        GPBUtil::checkUint64($var);
        $this->from_tick = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 to_tick = 2;</code>
     * @return int|string
     */
    public function getToTick()
    {
        return $this->to_tick;
    }

    /**
     * Generated from protobuf field <code>uint64 to_tick = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setToTick($var)
    {
        GPBUtil::checkUint64($var);
        $this->to_tick = $var;

        return $this;
    }

    /**
     * how far the jump was
     *
     * Generated from protobuf field <code>double distance = 3;</code>
     * @return float
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * how far the jump was
     *
     * Generated from protobuf field <code>double distance = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDistance($var)
    {
        GPBUtil::checkDouble($var);
        $this->distance = $var;

        return $this;
    }

}

