<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.UniverseSnapshot</code>
 */
class UniverseSnapshot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     */
    protected $universe_id = 0;
    /**
     * Generated from protobuf field <code>uint64 tick = 2;</code>
     */
    protected $tick = 0;
    /**
     * Generated from protobuf field <code>string state_vector_json = 3;</code>
     */
    protected $state_vector_json = '';
    /**
     * Generated from protobuf field <code>double entropy = 4;</code>
     */
    protected $entropy = 0.0;
    /**
     * Generated from protobuf field <code>double stability_index = 5;</code>
     */
    protected $stability_index = 0.0;
    /**
     * Generated from protobuf field <code>string metrics_json = 6;</code>
     */
    protected $metrics_json = '';
    /**
     * Generated from protobuf field <code>double sci = 7;</code>
     */
    protected $sci = 0.0;
    /**
     * Generated from protobuf field <code>double instability_gradient = 8;</code>
     */
    protected $instability_gradient = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $universe_id
     *     @type int|string $tick
     *     @type string $state_vector_json
     *     @type float $entropy
     *     @type float $stability_index
     *     @type string $metrics_json
     *     @type float $sci
     *     @type float $instability_gradient
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     * @return int|string
     */
    public function getUniverseId()
    {
        return $this->universe_id;
    }

    /**
     * Generated from protobuf field <code>uint64 universe_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUniverseId($var)
    {
        GPBUtil::checkUint64($var);
        $this->universe_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tick = 2;</code>
     * @return int|string
     */
    public function getTick()
    {
        return $this->tick;
    }

    /**
     * Generated from protobuf field <code>uint64 tick = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTick($var)
    {
        GPBUtil::checkUint64($var);
        $this->tick = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string state_vector_json = 3;</code>
     * @return string
     */
    public function getStateVectorJson()
    {
        return $this->state_vector_json;
    }

    /**
     * Generated from protobuf field <code>string state_vector_json = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStateVectorJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->state_vector_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double entropy = 4;</code>
     * @return float
     */
    public function getEntropy()
    {
        return $this->entropy;
    }

    /**
     * Generated from protobuf field <code>double entropy = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setEntropy($var)
    {
        GPBUtil::checkDouble($var);
        $this->entropy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double stability_index = 5;</code>
     * @return float
     */
    public function getStabilityIndex()
    {
        return $this->stability_index;
    }

    /**
     * Generated from protobuf field <code>double stability_index = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setStabilityIndex($var)
    {
        GPBUtil::checkDouble($var);
        $this->stability_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string metrics_json = 6;</code>
     * @return string
     */
    public function getMetricsJson()
    {
        return $this->metrics_json;
    }

    /**
     * Generated from protobuf field <code>string metrics_json = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMetricsJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->metrics_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double sci = 7;</code>
     * @return float
     */
    public function getSci()
    {
        return $this->sci;
    }

    /**
     * Generated from protobuf field <code>double sci = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setSci($var)
    {
        GPBUtil::checkDouble($var);
        $this->sci = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double instability_gradient = 8;</code>
     * @return float
     */
    public function getInstabilityGradient()
    {
        return $this->instability_gradient;
    }

    /**
     * Generated from protobuf field <code>double instability_gradient = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setInstabilityGradient($var)
    {
        GPBUtil::checkDouble($var);
        $this->instability_gradient = $var;

        return $this;
    }

}

