<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace Worldos\Simulation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>worldos.simulation.WorldConfig</code>
 */
class WorldConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 world_id = 1;</code>
     */
    protected $world_id = 0;
    /**
     * Generated from protobuf field <code>string origin = 2;</code>
     */
    protected $origin = '';
    /**
     * Generated from protobuf field <code>string axiom_json = 3;</code>
     */
    protected $axiom_json = '';
    /**
     * Generated from protobuf field <code>string world_seed_json = 4;</code>
     */
    protected $world_seed_json = '';
    /**
     * Generated from protobuf field <code>.worldos.simulation.KernelGenome genome = 5;</code>
     */
    protected $genome = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $world_id
     *     @type string $origin
     *     @type string $axiom_json
     *     @type string $world_seed_json
     *     @type \Worldos\Simulation\KernelGenome $genome
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worldos\Simulation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 world_id = 1;</code>
     * @return int|string
     */
    public function getWorldId()
    {
        return $this->world_id;
    }

    /**
     * Generated from protobuf field <code>uint64 world_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorldId($var)
    {
        GPBUtil::checkUint64($var);
        $this->world_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string origin = 2;</code>
     * @return string
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    /**
     * Generated from protobuf field <code>string origin = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkString($var, True);
        $this->origin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string axiom_json = 3;</code>
     * @return string
     */
    public function getAxiomJson()
    {
        return $this->axiom_json;
    }

    /**
     * Generated from protobuf field <code>string axiom_json = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAxiomJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->axiom_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string world_seed_json = 4;</code>
     * @return string
     */
    public function getWorldSeedJson()
    {
        return $this->world_seed_json;
    }

    /**
     * Generated from protobuf field <code>string world_seed_json = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWorldSeedJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->world_seed_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.worldos.simulation.KernelGenome genome = 5;</code>
     * @return \Worldos\Simulation\KernelGenome|null
     */
    public function getGenome()
    {
        return $this->genome;
    }

    public function hasGenome()
    {
        return isset($this->genome);
    }

    public function clearGenome()
    {
        unset($this->genome);
    }

    /**
     * Generated from protobuf field <code>.worldos.simulation.KernelGenome genome = 5;</code>
     * @param \Worldos\Simulation\KernelGenome $var
     * @return $this
     */
    public function setGenome($var)
    {
        GPBUtil::checkMessage($var, \Worldos\Simulation\KernelGenome::class);
        $this->genome = $var;

        return $this;
    }

}

