<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldos/simulation.proto

namespace GPBMetadata\Worldos;

class Simulation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
≥!
worldos/simulation.protoworldos.simulation"a
ObserveRequest
universe_id (

zone_index (
	intensity (
state_input ("l
ObserveResponse

ok (
error_message (	6
snapshot (2$.worldos.simulation.UniverseSnapshot"0
MergeRequest
state_a (
state_b ("j
MergeResponse

ok (
error_message (	6
snapshot (2$.worldos.simulation.UniverseSnapshot"Ä
AdvanceRequest
universe_id (
ticks (
state_input (5
world_config (2.worldos.simulation.WorldConfig"é
WorldConfig
world_id (
origin (	

axiom_json (	
world_seed_json (	0
genome (2 .worldos.simulation.KernelGenome"è
KernelGenome
diffusion_rate (
entropy_coefficient (
mutation_rate (
attractor_gravity (
complexity_bonus ("l
AdvanceResponse

ok (
error_message (	6
snapshot (2$.worldos.simulation.UniverseSnapshot"ª
UniverseSnapshot
universe_id (
tick (
state_vector_json (	
entropy (
stability_index (
metrics_json (	
sci (
instability_gradient ("K
BatchAdvanceRequest4
requests (2".worldos.simulation.AdvanceRequest"N
BatchAdvanceResponse6
	responses (2#.worldos.simulation.AdvanceResponse".
TrajectoryPoint
tick (
state ("n
TrajectoryAnalysisRequest3
points (2#.worldos.simulation.TrajectoryPoint
recurrence_threshold ("â
TrajectoryAnalysisResponse

is_bounded (
is_recurrent (
recurrence_rate (
max_lyapunov_estimate (
trajectory_variance (
basin_center (
basin_radius (@
regime_transitions (2$.worldos.simulation.RegimeTransition"H
RegimeTransition
	from_tick (
to_tick (
distance ("=
EvaluateRulesRequest

state_json (	
	rules_dsl (	"P
EvaluateRulesResponse

ok (
error_message (	
outputs_json (	"æ
ProcessActorsSoaRequest
tick (
ids (
zone_ids (
hunger (
energy (
fear (
trauma (
heroic_types (
lineage_ids	 (
memes
 ("_
ActorSoaOutput
	action_id (

new_hunger (

new_energy (

new_trauma ("r
ProcessActorsSoaResponse

ok (
error_message (	3
outputs (2".worldos.simulation.ActorSoaOutput"°
ProcessFieldsV7Request
fields (
neighbor_counts (
neighbor_offsets (
	neighbors (
diffusion_rate (
preservation_rate (")
ProcessFieldsV7Response
fields ("É
ComputeMetabolismGridRequest
populations (
	biomasses (

industries (

efficiency (
base_energy ("r
ComputeMetabolismGridResponse
total_waste (
populations (
	biomasses (
net_energies ("_
!CalculateVocationAlignmentRequest
actor_motivation_json (	
target_profile_json (	"7
"CalculateVocationAlignmentResponse
	alignment ("2
GetCombinedGravityRequest
rulesets_json (	"-
GetCombinedGravityResponse
gravity (2°	
SimulationEngineR
Advance".worldos.simulation.AdvanceRequest#.worldos.simulation.AdvanceResponseL
Merge .worldos.simulation.MergeRequest!.worldos.simulation.MergeResponseR
Observe".worldos.simulation.ObserveRequest#.worldos.simulation.ObserveResponsea
BatchAdvance\'.worldos.simulation.BatchAdvanceRequest(.worldos.simulation.BatchAdvanceResponser
AnalyzeTrajectory-.worldos.simulation.TrajectoryAnalysisRequest..worldos.simulation.TrajectoryAnalysisResponsed
EvaluateRules(.worldos.simulation.EvaluateRulesRequest).worldos.simulation.EvaluateRulesResponsem
ProcessActorsSoa+.worldos.simulation.ProcessActorsSoaRequest,.worldos.simulation.ProcessActorsSoaResponsej
ProcessFieldsV7*.worldos.simulation.ProcessFieldsV7Request+.worldos.simulation.ProcessFieldsV7Response|
ComputeMetabolismGrid0.worldos.simulation.ComputeMetabolismGridRequest1.worldos.simulation.ComputeMetabolismGridResponseã
CalculateVocationAlignment5.worldos.simulation.CalculateVocationAlignmentRequest6.worldos.simulation.CalculateVocationAlignmentResponses
GetCombinedGravity-.worldos.simulation.GetCombinedGravityRequest..worldos.simulation.GetCombinedGravityResponseB
worldos.simulationPbproto3'
        , true);

        static::$is_initialized = true;
    }
}

